os:  osx
language: java        #语言说明
jdk: oraclejdk8          #jdk版本
sudo: required           #权限要求
#env:                 #环境变量
global:
- ANDROID_API=29
- EMULATOR_API=29
- ANDROID_BUILD_TOOLS=29.0.2
- ADB_INSTALL_TIMEOUT=5 # minutes
android:             #Android 环境要求
components:
- tools
- platform-tools
- build-tools-$ANDROID_BUILD_TOOLS
- android-$ANDROID_API
- android-$EMULATOR_API
- extra-google-m2repository
- extra-android-m2repository        # 配置design 库 
- addon-google_apis-google-19       # 配置google play services
- sys-img-armeabi-v7a-android-$ANDROID_API
- sys-img-armeabi-v7a-android-$EMULATOR_API
licenses:               #内容许可添加
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

#####
before_script:
- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator

#########
env:
    bundle_id: com.cuilingshi.fileextract
    callback_url: http://api-mas-admin-test.yodo1.com/api/mas/task/async/3258d827-e7bc-4cf4-98f2-f84e4b3f0ffe
    sdk_key: rNHXebCtrUWyeDeAihKoDCmwM9sL2WfshXTVHs-7N0yUBE4D0KtcycoTQgE7Ha2a9CsCn9WI22ZwsJQ29h6LzI
    app_name: Unzip - zip file opener
    
cache:
  bundler: true
  directories:
    - Carthage

script: "sh automate.sh $bundle_id $app_name $callback_url $sdk_key"
